#!/bin/bash

./basic/core.sh
./basic/fish.sh
./basic/rfkill.sh
./explorer-files/ranger.sh
./explorer-files/thunar.sh
./fonts/font.sh
./suckless/dwm.sh
./suckless/surf.sh
./suckless/dbar.sh
./suckless/dmenu.sh
./suckless/dshortcuts.sh
./suckless/slock.sh
./suckless/st.sh
./programming/lazy-docker.sh
./programming/lazy-git.sh
./programming/lazy-npm.sh
./programming/mongo.sh
./programming/nodejs-npm.sh
./programming/nvim.sh
./programming/obsidian.sh
./programming/postman.sh
./programming/sublime-text.sh
./programming/vim.sh
./programming/vscode.sh
./programming/raspberry-pi-imager.sh
./programming/filezilla.sh
./basic/bash.sh
./basic/uninstall.sh
